config/routes.rb
Rails.application.routes.draw do
 
  post 'comments/new'
  post 'comments/create'
  get 'comments/edit'
  get 'comments/update'
  get 'comments/destroy'
  get 'comments/show'
  get 'publish_event'=>'events#publish_event', as:'publish_event'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root 'events#index'
  post'update_event/:id'=>'events#update_event', as:'update_event'
  post 'destroy_event/:id'=>'events#destroy_event', as:'destroy_event'
  resources :events 
  resources :friendships
  get 'like_event/:event_id' => 'events#like_event' , as:'like_event'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  # devise_scope :user do
  # root to: "devise/sessions#new"
  # end
  get 'guest_friend_request/:friend_id' => 'friendships#guest_friend_request', as:'guest_friend_request'
  get 'accept_friend_request/:friend_id' => 'friendships#accept_friend_request' , as:'accept_friend_request'
  get 'reject_friend_request/:friend_id' => 'friendships#reject_friend_request' , as:'reject_friend_request'
  #######################  event joining  #########################
  post 'request_join_event/:host_id' => 'events#request_join_event' , as:'request_join_event' 
  post 'accept_event_join_request/:event_id' => 'events#accept_event_join_request' ,as:'accept_event_join_request'
  post 'reject_event_join_request/:event_id' => 'events#reject_event_join_request' ,as:'reject_event_join_request'
 

 
    post '/get_events' =>'events#get_events'  
    post '/get_guests' => 'events#get_guests' 

  # Serve websocket cable requests in-process
   mount ActionCable.server => '/cable'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user 
  has_many :join_events , dependent: :destroy
  has_many :comments , dependent: :destroy
  has_many :likes
 
  delegate :email,:id,:name , to: :user
 
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :authenticate_user! 
	before_action :self_find , only:[:show, :edit,:destroy_event,:update_event,:edit,:update]
  def index
  	@users = User.all.where("id !=?",current_user.id).page(params[:page]).per(5)
  	@even_last=current_user.events.last
    @events=current_user.events.where("id != ?",@even_last.id).order('DESC') if @even_last
    
  end
   #######################   PUBLISH EVENT CREATED #######################
  def publish_event
  ActionCable.server.broadcast 'publish_channel',
        event_title: current_user.events.last.title,
        event_disc: current_user.events.last.discription,
        user: current_user.name

        redirect_to root_path , notice:"Event published !"
  end
  
  def new
  	@event=Event.new
  end

  def create
  	event=current_user.events.build(params_list)
      	if event.save
      		redirect_to root_path , notice:"Event generated successfully !"
      	else
      		head :ok
      	end
  end

  def like_event
    current_user.likes.create(event_id:params[:event_id])
    redirect_to event_path(params[:event_id]) ,notice:"You liked this event !"
  end

  def show
     guest=current_user.join_events.where(event_id:params[:id],status:"accept").present?
      if guest or JoinEvent.where(host_id:params[:id]).exists?
      @users = User.all.where("id !=?",current_user.id).page(params[:page]).per(5)
       else
      redirect_to root_path, notice:"You have not joined for this event !"
      end
  end
  def edit
    
  end
  def update
    @event.update(params_list)
    redirect_to root_path, notice:"Event updated successfully !"
  end
  def update_event
    render 'edit'
  end
  
  def destroy_event
  	@event.destroy
    redirect_to root_path, notice:"Event deleted successfully !"
  end

  def request_join_event
   event=Event.find(params[:event_id])
   restset= event.join_events.build(user_id:current_user.id,host_id:params[:host_id],status:"pending")
    if restset.save
      redirect_to root_path, notice:"Event join request send !"
    end
  end

  def accept_event_join_request
   event=Event.find(params[:event_id])
   event.join_events.where(user_id:params[:guest_id],host_id:current_user.id).update(status:"accept")
   redirect_to root_path, notice:"Event join request accepted !"
  end

  def reject_event_join_request
   event=Event.find(params[:event_id])
   event.join_events.where(user_id:params[:guest_id],host_id:current_user.id,status:"pending").first.destroy
   redirect_to root_path, notice:"Event join request rejected !"
  end
  
#############################    ACTIVE ADMIN ############
  def get_events
   p"-------------111------================---------------------#{params.inspect}==========="
    @host = User.find(params[:host_id])
    events = @host.events.pluck(:title,:id)

    render :json => {:events => events}
  end

  def get_guests
     p"-----------222--------================---------------------#{params.inspect}==========="
     @event = Event.find(params[:event_id])
     ids = Array.new
     s1=@event.join_events.all.pluck(:user_id)   #######  joined guest_id
     s2=Event.where(id:params[:event_id]).pluck(:user_id)     ##  host_id
     ids = s1+s2
   
     guests= User.where("id NOT IN (?)", ids).pluck(:name,:id)
    render :json => {:guests => guests}

  end
#####################################################  END 
  private
  def self_find
  	@event = Event.find(params[:id])
  end
  def params_list
  	 params.require(:event).permit(:title,:discription,:date)
  end

  
end

app/helpers/events_helper.rb
module EventsHelper
	def is_friend? guest_id
		if current_user.friendships.exists?(friend_id:guest_id) or current_user.inverse_friendships.exists?(user_id:guest_id)
	        return false
	    else
			return true
		end
	end

	def friend_request_list
		current_user.inverse_friendships.where(status:"pending")
	end

	def friend_list1
		current_user.friendships.where(status:"accept")
		#Friendship.where("(user_id=? or friend_id=?) and status=?",current_user,current_user.id,"accept")
	end
	def friend_list2
		current_user.inverse_friendships.where(status:"accept")
	end

	def event_count
		friend_list1.count + friend_list2.count
	end
  ################ notification for specific events  #####################
	def join_notification evnt_id
		event=Event.find(evnt_id)
		event.join_events.where(host_id:current_user.id,status:"pending")
	end
	def all_event
		current_user.events
	end

	def is_guest?(e_id)
	  current_user.join_events.where(event_id:e_id,status:"accept").present?	
	end
end

app/views/events/_form.html.erb
 <%=form_tag request_join_event_url(event.user_id) do %>

     <%= hidden_field_tag "event_id",event.id%>
     <%=submit_tag "Join Event !", class:"btn btn-default btn-lg btn-block"%>
 <%end%>

app/views/events/_friends.html.erb
<% @users.each do |user|%>
  <li class="list-group-item">
    <%= user.name%> 
    <%if is_friend?(user.id)%>
    <%=link_to"+",guest_friend_request_path(user.id),class:"navbar-right btn-info btn-xs" , style:"font-size:20px;"%>
    <main class="bg-info appearance" data-behavior="appear_away">nf</main>
    
    <% if user.online?%>
    <i class="badge glyphicon glyphicon-signal" style="background:green;">&nbsp;</i>
    <% end%>
    <%end%>
  </li>
  <% end %>
  <div class="apple_pagination" style="height:10%;">
  <%= paginate @users %>
  </div>
</ul>
<!--  ###############   Friend List  ################-->
<% if friend_list1.present?%>
<ul class="list-group">
    <% friend_list1.each do |friend|%>
    <%user=User.find(friend.friend_id)%>
     <li class="list-group-item"> <%= user.name%>
       <% if user.online?%>
    <i class="badge bg-success glyphicon glyphicon-signal" style="background:green;">&nbsp;</i>
    <% end%>
     	<span class="badge"><%=user.events.count %></span>

     </li>
    <% end %>
</ul>
<% end%>

<% if friend_list2.present?%>
<ul class="list-group">
    <% friend_list2.each do |friend|%>
     <%user=User.find(friend.user_id)%>
     <li class="list-group-item"> <%= user.name%>
       <% if user.online?%>
    <i class="badge bg-success glyphicon glyphicon-signal" style="background:green;">&nbsp;</i>
    <% end%>
     	<span class="badge"><%=user.events.count %></span>

     </li>
    <% end %>
</ul>
<% end%>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/edit.html.erb
<div class="panel panel-primary col-md-7" style="margin-left:20%;">
 <div class="panel-heading">
    <h3 class="panel-title">Update Event
     </h3>
    </div>
<div class="panel-body">
<%= form_for(@event) do |f| %>
 
<div class="form-group">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :title ,class:"form-control", maxlength:30 , required:true%>
  </div>
  </div>
  <div class="form-group">
  <div class="field">
    <%= f.label :discription %><br>
    <%= f.text_area :discription , required:true, class:"form-control"%>
  </div>
  </div>
  <div class="form-group">
  <div class="field">
  <span class="add-on">
      <i data-time-icon="icon-time" data-date-icon="glyphicon-calendar">
      </i>
    </span>
     <%= f.label :event_date %><br>
    <%= f.text_field :date , required:true, id:"datetimepicker"%>
    

</div>
</div>

  <div class="actions">
    <%= f.submit "Create Event",class:"btn btn-primary"%>
  </div>
<% end %>
<br>
<%= link_to 'Cancel', root_path , class:"btn btn-primary", style:" margin-top:-50px; float:right;"%>
   
</div></div>

app/views/events/index.html.erb
<div class="col-md-9"><center>
		<div class="jumbotron">
		<% if @even_last.present?%>
		  <h1><%= @even_last.title%></h1>
		  <p><%= @even_last.discription%></p>
		  <p><%=link_to"Publish",publish_event_path%></p>
		  <% else%>
		  <p>No events available ! &nbsp;
		  <%=link_to"Create New Event",new_event_path,class:"btn btn-default btn-lg "%></p>
		  <% end%>
		</div></center>

 <%if myevent=current_user.events%>	
 <% a=0%>
 <div class="col-md-3">
 <% myevent.each do |event|%>	
   <% if a%2==0%>
	<div class="panel panel-primary">
	
	  <div class="panel-heading">
	   
	    <h3 class="panel-title"><%= event.title%>
	    	
	    </h3>
	  </div>
	  <div class="panel-body">
	    <%= event.discription%><%=link_to"Read more..",event_path(event)%>
	    <span class="badge"><%= event.date.to_formatted_s(:rfc822) if event.date%></span>
       <ul class="nav nav-pills">
        <li><%=button_to"delete",destroy_event_path(event) ,class:"btn btn-primary btn-sm"%></li>
        
        <li><%=button_to"update",update_event_path(event),class:"btn btn-primary btn-sm"%></li>
        </ul>
	  </div>
	</div>
   <% end%>
   <% a=a+1%>
   <% end %>
   </div>
  <% end %>



  <%if myevent=current_user.events%>	
 <% a=0%>
 <div class="col-md-3">
 <% myevent.each do |event|%>	
   <% unless a%2==0%>
	<div class="panel panel-primary">
	
	  <div class="panel-heading">
	   
	    <h3 class="panel-title"><%= event.title%></h3>
	  </div>
	  <div class="panel-body">
	    <%= event.discription%><%=link_to"Read more..",event_path(event)%>
	    <span class="badge"><%= event.date.to_formatted_s(:rfc822) if event.date%></span>
	    <ul class="nav nav-pills">
        <li><%=button_to"delete",destroy_event_path(event),class:"btn btn-primary btn-sm"%></li>
       
        <li><%=button_to"update",update_event_path(event),class:"btn btn-primary btn-sm"%></li>
        </ul>
	  </div>
	</div>
   <% end%>
   <% a=a+1%>
   <% end %>
   </div>
  <% end %>
  <!--================================  Others' Events ===========================-->

  <% if friend_list1.present?%>
   <div class="col-md-3">
   <% friend_list1.each do |frnd|%>

   <% friend=User.find(frnd.friend_id)%>
    <% if friend.events.present?%>
     <% friend.events.each do |event|%>
	<div class="panel panel-primary">
	
	  <div class="panel-heading">
	   
	    <h3 class="panel-title"><%= event.title%></h3>
	    <span class="badge"><%=link_to "Publish by #{User.find(event.user_id).name}"%></span>
	   
	  </div>
	  <div class="panel-body">
	    <%= event.discription%> <%=link_to"Read more..",event_path(event)%>
	    <span class="badge"><%= event.date.to_formatted_s(:rfc822) if event.date%></span>
	    
       <% if event.join_events.where(user_id:current_user.id,host_id:event.user_id,status:"pending").present?%>
      
       <div class="btn btn-default btn-lg btn-block"%>Join under process.. !</div>
       <%# end %>
       <% elsif event.join_events.where(user_id:current_user.id,host_id:event.user_id,status:"accept").present?%>
	    
	   <div class="btn btn-default btn-lg btn-block"%>You Joined.. !</div>
       <%# end %>
       <% else %> <%#event.join_events.where(user_id:current_user.id,host_id:frnd.friend_id).present?%>
	  
	   <%=form_tag request_join_event_url(event.user_id) do %>

        <%= hidden_field_tag "event_id",event.id%>
        <%=submit_tag "Join Event !", class:"btn btn-default btn-lg btn-block"%>

 	   <%end%>
 	   <% end %>
	  </div>
	</div>
	<% end %>
	<% end%>
	<% end%>
	</div>
  <%end %>

  <% if friend_list2.present?%>
   <div class="col-md-3">
   <% friend_list2.each do |frnd|%>

   <% friend=User.find(frnd.user_id)%>
    <% if friend.events.present?%>
     <% friend.events.each do |event|%>
	<div class="panel panel-primary">
	
	  <div class="panel-heading">
	   
	    <h3 class="panel-title"><%= event.title%></h3>
	    <span class="badge"><%=link_to "Publish by #{User.find(event.user_id).name}"%></span>
	  </div>
	  <div class="panel-body">
	    <%= event.discription%><%=link_to"Read more..",event_path(event)%>
	    <span class="badge"><%= event.date.to_formatted_s(:rfc822) if event.date%></span>
	    
	    <%#= render 'form', locals:{ :event => event} %>
	    
	    <% if event.join_events.where(user_id:current_user.id,host_id:event.user_id,status:"pending").present?%>
       
       <div class="btn btn-default btn-lg btn-block"%>Join under process !</div>
       
       <% elsif event.join_events.where(user_id:current_user.id,host_id:event.user_id,status:"accept").present?%>
	    <div class="btn btn-default btn-lg btn-block"%>You Joined !</div>
       <% else %><%# event.join_events.where(user_id:current_user.id,host_id:frnd.friend_id).present?%>
	   <%=form_tag request_join_event_url(event.user_id) do %>

        <%= hidden_field_tag "event_id",event.id%>
        <%=submit_tag "Join Event !", class:"btn btn-default btn-lg btn-block"%>

 	   <%end%>
 	   <% end %>
	  </div>
	</div>
	<% end %>
	<% end%>
	<% end%>
	</div>
  <%end %>
	
</div>
<!-- ====================   Friends List + User List ======================= -->
<div class="col-md-3">


<%= render "friends", @user%>

</div>

app/views/events/new.html.erb
<div class="panel panel-primary col-md-7" style="margin-left:20%;">
 <div class="panel-heading">
    <h3 class="panel-title">New Event
     </h3>
    </div>
<div class="panel-body">
<%= form_for(@event) do |f| %>
 
<div class="form-group">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :title ,class:"form-control", maxlength:30 , required:true%>
  </div>
  </div>
  <div class="form-group">
  <div class="field">
    <%= f.label :discription %><br>
    <%= f.text_area :discription , required:true, class:"form-control"%>
  </div>
  </div>
  <div class="form-group">
  <div class="field">
  <span class="add-on">
      <i data-time-icon="icon-time" data-date-icon="glyphicon-calendar">
      </i>
    </span>
     <%= f.label :event_date %><br>
    <%= f.text_field :date , required:true, id:"datetimepicker"%>
    

</div>
</div>

  <div class="actions">
    <%= f.submit "Create Event",class:"btn btn-primary"%>
  </div>
<% end %>
<br>
<%= link_to 'Cancel', root_path , class:"btn btn-primary", style:" margin-top:-50px; float:right;"%>
   
</div></div>

app/views/events/show.html.erb
<div class="panel panel-default col-md-6" style="margin-left:15%;">
  <div class="panel-heading"><h3><%=@event.title%>

    
    <% unless current_user.likes.exists?%>
    <%=link_to"   Like",like_event_path(@event),class:"btn btn-primary glyphicon glyphicon-hand-up", style:"float:right; width:10%;"%>
    <span class="badge" style="float:right;">
      <%=@event.likes.count%>
    </span>

    <%else%>
    <%=link_to" liked!","" ,class:"btn btn-primary glyphicon glyphicon-hand-up", style:"float:right; width:20%;"%>
    <span class="badge" style="float:right;">
      <%=@event.likes.count%>
    </span>
    
    <%end%></h3>
  </div>
  <div class="panel-body">
    <p><b>Discription :</b>
      <hr>
      <%=@event.discription%></p>
    </div>
    <hr>
   


    <table class="table table-hover ">
      <thead>Guest Comments <i  class="glyphicon glyphicon-comment"></i></thead>

      <% @event.comments.all.each do |comment| %>
     <tr>
          
        <td style="word-break:break-all;">
        <% if comment.user_id==current_user.id%>
          <%= comment.content%>
          <span class="badge">  
            <%=time_ago_in_words(comment.created_at)+" ago , by "+"#{User.find(comment.user_id).name}"%></span>
          </td>
          <%else%>
           <td style="word-break:break-all;">
           <%= comment.content%>
          <span class="badge">  
            <%=time_ago_in_words(comment.created_at)+" ago , by "+"#{User.find(comment.user_id).name}"%></span>
            <%end%>
          </td>
         
        </tr>

        <% end%>
          <tr><td></td>
          <td id="comments" data-channel="comments" data-event-id="<%= @event.id %>">
          </td>
        </tr>

      </table>
      
      <hr>
      <%= render'comments/form', locals:{ event: @event}%>
      <br>
      
      <%=link_to"< Back",root_path, class:"btn btn-default"%>
    </div>

<!--==================================   Friends list  ========================================-->
    <div class="col-md-4">
     <%= render'friends' , @user%>
    </div>