config/routes.rb
Rails.application.routes.draw do
 
  post 'comments/new'
  post 'comments/create'
  get 'comments/edit'
  get 'comments/update'
  get 'comments/destroy'
  get 'comments/show'
  get 'publish_event'=>'events#publish_event', as:'publish_event'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root 'events#index'
  post'update_event/:id'=>'events#update_event', as:'update_event'
  post 'destroy_event/:id'=>'events#destroy_event', as:'destroy_event'
  resources :events 
  resources :friendships
  get 'like_event/:event_id' => 'events#like_event' , as:'like_event'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  # devise_scope :user do
  # root to: "devise/sessions#new"
  # end
  get 'guest_friend_request/:friend_id' => 'friendships#guest_friend_request', as:'guest_friend_request'
  get 'accept_friend_request/:friend_id' => 'friendships#accept_friend_request' , as:'accept_friend_request'
  get 'reject_friend_request/:friend_id' => 'friendships#reject_friend_request' , as:'reject_friend_request'
  #######################  event joining  #########################
  post 'request_join_event/:host_id' => 'events#request_join_event' , as:'request_join_event' 
  post 'accept_event_join_request/:event_id' => 'events#accept_event_join_request' ,as:'accept_event_join_request'
  post 'reject_event_join_request/:event_id' => 'events#reject_event_join_request' ,as:'reject_event_join_request'
 

 
    post '/get_events' =>'events#get_events'  
    post '/get_guests' => 'events#get_guests' 

  # Serve websocket cable requests in-process
   mount ActionCable.server => '/cable'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HostEventGuest</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    
  </head>

  <body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <%= link_to "My@~Events ", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
      <%unless current_user%>
        <li>
        <%= link_to "Sign up", new_user_registration_path%><br />
        </li>
        <li>
        <%= link_to "Log in", new_user_session_path %><br />
        </li>
        <% else %>
         <li><a href="#"class="navbar-brand" > HOST:<%= current_user.name%></a>
         <!--  ======    TO ShOW USER IS ONLINE   OR  NOT -->
         

         <%if current_user.online?%>
           <span class="badge glyphicon glyphicon-ok-sign bg-success">online</span>
           <% else%>
           <span class="badge glyphicon glyphicon-remove-sign bg-danger">offline</span>
         <%end%>
         
         </li>

         <li><%=link_to"Create New Event",new_event_path%></li>

         <!-- =================        Event notification show   ===================-->
        <li class="dropdown" style="width:50%;">
          <a href="#"  class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Event Join Request <span class="caret"></span></a>
              <ol class="dropdown-menu"">
               <% if myevents=all_event%>
               <% myevents.each do |event|%>
                <%evnt=join_notification(event.id)%>
                <% if evnt.present?%>

                  <div class="panel panel-primary">
                  <div class="panel-heading">
                    <h3 class="panel-title"><%=event.title%><span class="caret"></span> <span class="badge"><%=evnt.count%></span></h3>
                  </div>
                  <div class="panel-body">
                  <ul class="list-group">
                 <% evnt.each do |member|%>
                  
                    <li class="list-group-item">
                     <p> <%="Join request by : #{User.find(member.user_id).name}, at '#{time_ago_in_words(member.created_at)}' ago"%>
                     <ul class="breadcrumb"><li>
                       <%=form_tag accept_event_join_request_url(event.id) do %>

                          <%= hidden_field_tag "guest_id",member.user_id%>
                          <%=submit_tag "accept !"%>

                       <%end%></li><li>

                       <%=form_tag reject_event_join_request_url(event.id) do %>

                          <%= hidden_field_tag "guest_id",member.user_id%>
                          <%=submit_tag "reject !"%>

                       <%end%></li></ul>
                       </p>
                
                    </li>
                 <% end %>
                 </ul>
                 </div>
                </div>
                <% end %>
               <% end%>
              <% end %>
              </ol>
         
        </li>
   
        </ul>
         <ul class="nav navbar-nav navbar-right">
          

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Friendship Request <span class="caret"></span><span class="badge"><%=friend_request_list.count if friend_request_list.present?%></span></a>
              <ul class="dropdown-menu">
               <% if friend_request_list.present?%>
               <% friend_request_list.each do |list|%>
               <li>
                    <ul class="breadcrumb">
                      <li><h4><%=link_to User.find(list.user_id).name%></h4></li>
                      <li><%=link_to "Accept",accept_friend_request_path(list.user_id)%>/
                      <%=link_to "Deny",reject_friend_request_path(list.user_id)%></li>
                    </ul>
              
               </li>
              <%end%>
               <% end %>
              </ul>
        
       </li>



       <li>
          <%= link_to "Log Out", users_sign_out_path , method: :get%>
        </li>
    </ul>
      
<%end%>
    </div>
  </div>
  </nav>
  <div class="alert alert-info" id="recent_event">
 <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <%= notice%></div>
 <%= yield %>

<script type="text/javascript">
  $(function() {
    $('#datetimepicker').datetimepicker({
      language: 'en',
      pick12HourFormat: true,
      pickTime: true,
      format:'yyyy-MM-dd HH:mm:ss'
    });
  });


    $(function() {
      $('#datetimepicker1').datetimepicker({
        language: 'en',
        format:'yyyy-MM-dd'
      });
    });

  /*$("#datetimepicker1").datepicker({
    beforeShow: function (input, inst) {
        setTimeout(function () {
            inst.dpDiv.css({
                top: 400,
                left: 200
            });
        }, 0);
    }
});*/
// $('#datetimepicker1').datepicker({
//     beforeShow: function(input, inst)
//     {
//         inst.dpDiv.css({marginTop: -input.offsetHeight + 'px', marginLeft: input.offsetWidth + 'px'});
//     }
// });
</script>
<%if current_user%>
<!-- Start of LiveChat (www.livechatinc.com) code -->
<script type="text/javascript">
window.__lc = window.__lc || {};
window.__lc.license = 8109691;
(function() {
  var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
  lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);
})();
</script>
<%end%>
<!-- End of LiveChat code -->
</body>
</html>